version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - frontend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - frontend_network

  api:
    stdin_open: true
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: nodejs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    restart: always
    networks:
      - frontend_network
    command: su -c "npx prisma migrate dev --name init && npm start"

volumes:
  postgres-data:
  pgadmin-data:

networks:
  frontend_network:
